# Dependabot configuration for automated dependency updates
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Node.js backend API dependencies
  - package-ecosystem: "npm"
    directory: "/marketing/backend/api"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    assignees:
      - "backend-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Group security updates together
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
    # Allow auto-merge for patch updates of trusted packages
    allow:
      - dependency-type: "direct"
        update-type: "security-update"
      - dependency-type: "indirect"
        update-type: "security-update"
    # Ignore major version updates for these packages (manual review required)
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]

  # Python Reddit service dependencies
  - package-ecosystem: "pip"
    directory: "/marketing/services/reddit-service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    assignees:
      - "backend-team"
    commit-message:
      prefix: "deps(python)"
    labels:
      - "dependencies"
      - "python"
      - "reddit-service"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/marketing/backend/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "security-team"
      - "devops-team"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"