{{- if .Values.canary.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "ofm-social-os.fullname" . }}-api-rollout
  labels:
    {{- include "ofm-social-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ add .Values.api.replicaCount .Values.api.canaryReplicaCount }}
  strategy:
    canary:
      canaryService: {{ include "ofm-social-os.fullname" . }}-api-canary
      stableService: {{ include "ofm-social-os.fullname" . }}-api
      trafficRouting:
        nginx:
          stableIngress: {{ include "ofm-social-os.fullname" . }}-api
          annotationPrefix: nginx.ingress.kubernetes.io
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: always
            canary-by-cookie: canary
      steps:
        - setWeight: {{ .Values.canary.weight }}
        - pause:
            duration: {{ .Values.canary.duration }}
        {{- if .Values.canary.analysis.enabled }}
        - analysis:
            templates:
              - templateName: {{ include "ofm-social-os.fullname" . }}-success-rate
            args:
              - name: service-name
                value: {{ include "ofm-social-os.fullname" . }}-api
        {{- end }}
        - setWeight: 50
        - pause:
            duration: 30m
        - setWeight: 100
      analysis:
        templates:
          - templateName: {{ include "ofm-social-os.fullname" . }}-success-rate
          - templateName: {{ include "ofm-social-os.fullname" . }}-latency-p95
          - templateName: {{ include "ofm-social-os.fullname" . }}-webhook-signature
        args:
          - name: service-name
            value: {{ include "ofm-social-os.fullname" . }}-api-canary
        startingStep: 2
        interval: {{ .Values.canary.analysis.interval }}
        count: {{ .Values.canary.analysis.threshold }}
        successCondition: "{{- .Values.canary.analysis.successCondition }}"
        failureLimit: 3
      scaleDownDelaySeconds: 30
      abortScaleDownDelaySeconds: 30
  selector:
    matchLabels:
      {{- include "ofm-social-os.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ofm-social-os.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ofm-social-os.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: api
          image: "{{ .Values.global.imageRegistry }}{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment }}
            - name: FEATURE_FLAGS
              value: {{ .Values.featureFlags | toJson | quote }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "ofm-social-os.fullname" . }}-config
            - secretRef:
                name: {{ include "ofm-social-os.fullname" . }}-secret
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
# Service for stable version
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ofm-social-os.fullname" . }}-api
  labels:
    {{- include "ofm-social-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ofm-social-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
# Service for canary version
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ofm-social-os.fullname" . }}-api-canary
  labels:
    {{- include "ofm-social-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    version: canary
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ofm-social-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}