apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ofm-social-os.fullname" . }}-secret
  labels:
    {{- include "ofm-social-os.labels" . | nindent 4 }}
type: Opaque
data:
  # Platform API credentials (base64 encoded)
  {{- if .Values.secrets.INSTAGRAM_CLIENT_ID }}
  INSTAGRAM_CLIENT_ID: {{ .Values.secrets.INSTAGRAM_CLIENT_ID | b64enc }}
  {{- end }}
  {{- if .Values.secrets.INSTAGRAM_CLIENT_SECRET }}
  INSTAGRAM_CLIENT_SECRET: {{ .Values.secrets.INSTAGRAM_CLIENT_SECRET | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.TIKTOK_CLIENT_ID }}
  TIKTOK_CLIENT_ID: {{ .Values.secrets.TIKTOK_CLIENT_ID | b64enc }}
  {{- end }}
  {{- if .Values.secrets.TIKTOK_CLIENT_SECRET }}
  TIKTOK_CLIENT_SECRET: {{ .Values.secrets.TIKTOK_CLIENT_SECRET | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.X_API_KEY }}
  X_API_KEY: {{ .Values.secrets.X_API_KEY | b64enc }}
  {{- end }}
  {{- if .Values.secrets.X_API_SECRET }}
  X_API_SECRET: {{ .Values.secrets.X_API_SECRET | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.REDDIT_CLIENT_ID }}
  REDDIT_CLIENT_ID: {{ .Values.secrets.REDDIT_CLIENT_ID | b64enc }}
  {{- end }}
  {{- if .Values.secrets.REDDIT_CLIENT_SECRET }}
  REDDIT_CLIENT_SECRET: {{ .Values.secrets.REDDIT_CLIENT_SECRET | b64enc }}
  {{- end }}
  
  # LLM API keys
  {{- if .Values.secrets.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc }}
  {{- end }}
  {{- if .Values.secrets.ANTHROPIC_API_KEY }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.ANTHROPIC_API_KEY | b64enc }}
  {{- end }}
  
  # AWS credentials
  {{- if .Values.secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  {{- end }}
  {{- if .Values.secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
  {{- end }}
  
  # Monitoring and alerting
  {{- if .Values.secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.SLACK_WEBHOOK_URL | b64enc }}
  {{- end }}
  {{- if .Values.secrets.PAGERDUTY_SERVICE_KEY }}
  PAGERDUTY_SERVICE_KEY: {{ .Values.secrets.PAGERDUTY_SERVICE_KEY | b64enc }}
  {{- end }}
  
  # JWT and encryption keys
  {{- if .Values.secrets.JWT_SECRET }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.ENCRYPTION_KEY }}
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY | b64enc }}
  {{- else }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  # Webhook verification secrets
  {{- if .Values.secrets.WEBHOOK_SECRET }}
  WEBHOOK_SECRET: {{ .Values.secrets.WEBHOOK_SECRET | b64enc }}
  {{- else }}
  WEBHOOK_SECRET: {{ randAlphaNum 32 | b64enc }}
  {{- end }}